// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace reactivemarkets.papi
{

public enum FeedType : short
{
  Default = 0,
  Trade = 1,
};


}
