// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace reactivemarkets.papi
{

public enum Side : sbyte
{
  Sell = -1,
  None = 0,
  Buy = 1,
};


}
